import type { Theme } from '@mui/material/styles';

export const styles = {
  container: {
    padding: (theme: Theme) => theme.spacing(3),
    maxWidth: '1400px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    height: 'calc(100vh - 80px)',
    boxSizing: 'border-box',
  },
  header: {
    marginBottom: (theme: Theme) => theme.spacing(2),
    fontWeight: 600,
  },
  formCard: {
    padding: (theme: Theme) => theme.spacing(4),
    display: 'flex',
    flexDirection: 'column',
    gap: (theme: Theme) => theme.spacing(3),
    boxShadow: (theme: Theme) => theme.shadows[3],
    borderRadius: (theme: Theme) => (theme.shape.borderRadius as number) * 2,
    background: (theme: Theme) => theme.palette.background.paper,
    maxWidth: '600px',
    margin: '40px auto 0 auto',
    width: '100%',
  },
  formTitle: {
    fontWeight: 600,
  },
  errorCard: {
    padding: (theme: Theme) => theme.spacing(4),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: (theme: Theme) => theme.spacing(2),
    boxShadow: (theme: Theme) => theme.shadows[3],
    borderRadius: (theme: Theme) => (theme.shape.borderRadius as number) * 2,
    background: (theme: Theme) => theme.palette.background.paper,
    maxWidth: '550px',
    margin: '40px auto 0 auto',
    textAlign: 'center',
  },
  errorIcon: {
    fontSize: 56,
  },
  errorActions: {
    display: 'flex',
    gap: (theme: Theme) => theme.spacing(2),
    marginTop: (theme: Theme) => theme.spacing(2),
  },
  callLayout: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    height: '100%',
  },
  callTitle: {
    fontWeight: 600,
  },
  callActions: {
    display: 'flex',
    gap: (theme: Theme) => theme.spacing(1),
  },
  callHeaderBar: {
    display: 'flex',
    alignItems: 'center',
    justify: 'space-between',
    padding: (theme: Theme) => theme.spacing(1.5, 2),
    background: (theme: Theme) => theme.palette.background.paper,
    borderRadius: (theme: Theme) => `${theme.shape.borderRadius}px ${theme.shape.borderRadius}px 0 0`,
    border: (theme: Theme) => `1px solid ${theme.palette.divider}`,
    borderBottom: 'none',
  },
  jitsiContainer: {
    flexGrow: 1,
    width: '100%',
    minHeight: '500px',
    borderRadius: (theme: Theme) => `0 0 ${theme.shape.borderRadius}px ${theme.shape.borderRadius}px`,
    overflow: 'hidden',
    border: (theme: Theme) => `1px solid ${theme.palette.divider}`,
    background: (theme: Theme) => theme.palette.common.black,
  },
  loadingBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: (theme: Theme) => theme.spacing(2),
    minHeight: '400px',
  },
};
