import type { Theme } from '@mui/material/styles';

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: 'calc(100vh - 64px)',
    minHeight: 0,
    boxSizing: 'border-box',
    backgroundColor: (theme: Theme) => theme.palette.background.default,
    '&:fullscreen': {
      height: '100vh',
      backgroundColor: (theme: Theme) => theme.palette.background.default,
    },
  },
  emptyTitle: {
    fontWeight: 600,
  },
  emptyCard: {
    padding: (theme: Theme) => theme.spacing(4),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: (theme: Theme) => theme.spacing(1),
    boxShadow: (theme: Theme) => theme.shadows[3],
    borderRadius: (theme: Theme) => (theme.shape.borderRadius as number) * 2,
    background: (theme: Theme) => theme.palette.background.paper,
    maxWidth: '520px',
    margin: 'auto',
    textAlign: 'center',
  },
  errorCard: {
    padding: (theme: Theme) => theme.spacing(4),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: (theme: Theme) => theme.spacing(2),
    boxShadow: (theme: Theme) => theme.shadows[3],
    borderRadius: (theme: Theme) => (theme.shape.borderRadius as number) * 2,
    background: (theme: Theme) => theme.palette.background.paper,
    maxWidth: '550px',
    margin: '40px auto 0 auto',
    textAlign: 'center',
  },
  errorIcon: {
    fontSize: 56,
  },
  errorActions: {
    display: 'flex',
    gap: (theme: Theme) => theme.spacing(2),
    marginTop: (theme: Theme) => theme.spacing(2),
  },
  callLayout: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    height: '100%',
    minHeight: 0,
  },
  callTitle: {
    fontWeight: 600,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  callActions: {
    display: 'flex',
    gap: (theme: Theme) => theme.spacing(1),
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  callHeaderBar: {
    display: 'flex',
    alignItems: 'center',
    justify: 'space-between',
    gap: (theme: Theme) => theme.spacing(2),
    padding: (theme: Theme) => theme.spacing(1.5, 2),
    background: (theme: Theme) => theme.palette.background.paper,
    border: (theme: Theme) => `1px solid ${theme.palette.divider}`,
    borderBottom: 'none',
    flexShrink: 0,
    position: 'relative',
    zIndex: 1,
    '@media (max-width: 640px)': {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  jitsiContainer: {
    flexGrow: 1,
    width: '100%',
    minHeight: 0,
    overflow: 'hidden',
    border: (theme: Theme) => `1px solid ${theme.palette.divider}`,
    background: (theme: Theme) => theme.palette.common.black,
    '& iframe': {
      display: 'block',
      width: '100%',
      height: '100%',
    },
  },
  loadingBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: (theme: Theme) => theme.spacing(2),
    minHeight: '400px',
  },
};
